### PR TITLE
Add support for generic file uploads

### PR DESCRIPTION
**Pull request by Senither**
This adds support for generic file uploads that don't match the existing categories like images, files and shorten URLs, files uploaded as generic files will be previewed when accessed with an icon matching the file type, and some information about the file such as its name, file size, MD5 and SHA1 hashes, this PR is based off the suggestion in #20.

TODO List:

- [x] Create file preview before downloading them.
    - The preview should include the icon matching the file extension, and some general information about the file such as the original name, file size, and hashes.
- [x] Create files observer to delete files from disk.
- [x] Add file settings to the control panel.
- [x] Add file scopes to the API tokens page.
- [x] Add support for uploading files via the UI.
- [x] Add support for uploading files via the API.
- [x] Ensure all UI components works in both light and dark mode

### CODE REVIEW

**Comment by teo0781** [comment]
Would it be possible to preview .zip file contents?

**Comment by Senither** [comment]
Not with the initial release of this feature, however, it's something that I can add later down the line.

**Comment by teo0781** [comment]
It's already complete?
If so, that was suprisingly quick.

**Comment by Senither** [comment]
Yup^^ Just need to update the wiki with some info, but the actual functionality is done.

**Pull request merged**
